### ISSUE TITLE
Fluent API

### ISSUE THREAD

**Issue by MuNet** [DonPangPang/Soda.Http#1]
有文件上传与下载的方法吗？

**Comment by wosledon** [comment]
写了文件上传的方法，下载的我还真的忘了！😂不过我预留了GetXXXResponseAsync()，下载文件可以直接从response的content里拿

**Comment by MuNet** [comment]
> 写了文件上传的方法，下载的我还真的忘了！😂不过我预留了GetXXXResponseAsync()，下载文件可以直接从response的content里拿

加上呗 😂

**Comment by wosledon** [comment]
好！下个版本！我想想怎么弄😂

**Comment by wosledon** [comment]
已经添加了哦，现在内置了一个download方法，可以下载文件
